version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "1q2w3e4r@#$"
      MSSQL_PID: "Developer"
      MSSQL_USER: "SA"
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - ~/mssql/logs:/var/opt/mssql/log
      - ~/mssql/data:/var/opt/mssql/data
